# Generated by Django 3.0.6 on 2020-05-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('discid', models.CharField(blank=True, max_length=255, null=True)),
                ('osuid', models.IntegerField(blank=True, null=True)),
                ('loluser', models.CharField(blank=True, max_length=255, null=True)),
                ('lolregion', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('passwd', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
